### ISSUE TITLE
Schematics?

### ISSUE THREAD

**Issue by Jenpatrick** [brianlevis/nerf-iron-dome#2]
Seemed feature complete... but would love to get some schematics and parts list for everything.  I have everything else ready to go.

You did a good think making this.

**Comment by brianlevis** [comment]
Hi!

Here is a link <https://a360.co/2Jig4f0> to a Fusion360 assembly that,
while incomplete, has a block Nerf model and wood pieces with correct
measurements (I think) for download in whatever CAD format.
Here is the parts list
<https://docs.google.com/document/d/1CbOCKuaJuKa1PlUHSESG5hxSh9v7ZApQfoIwh0dg4ak/edit?usp=sharing>
with
some Amazon links.
Here is a link <https://photos.app.goo.gl/LALiQSnzdtjJGJZq9> to some photos.

I built this with a jigsaw and a drill, and it was designed so that it
could be disassembled and packed in a suitcase because I don't have tools
where I normally live. 1/2" plywood was easy and cheap, but is a bit
heavier than I'd like.
The Arduino code is in arduino/GunController and some run scripts at
modes/face_detect.py, ball_tracking.py (adapted from the really helpful
pyimagesearch.com), and controller.py, powered by nerf_turret.py. The
turret is a bit jittery, but still quite functional- I'd like to eventually
implement an actual control model that accounts for the command response
latency.
This is hardly a polished project, but hopefully these are useful :D

-Brian

**Comment by Jenpatrick** [comment]
Amazing. And many thanks. It helps out a ton. I'm about to sleep and looking forward to the jigsaw part tomorrow. 

For the Rpi to Arduino control. And Arduino to server. How was that diagrammed out?

I can probably figure out a bunch of it. But I'd also be happy to contribute a build-it.md file after I get it all up. :)

**Comment by brianlevis** [comment]
I initially selected Arduino for turret control because I read that it did not have hardware-level PWM support, but I never actually tested RPi servo control. I mostly chose it because I was more familiar with the platform, and because I could solder resistors and connectors on to a custom PCB Arduino shield I had lying around.

In the current setup, the Arduino controls the motor relays, servos, and pin sensor. The Arduino sends a 'ready' byte over serial, and receives a fixed-length control instruction. It is also a useful abstraction that, given any set of high level inputs, will not perform any movements that break the hardware. The software doc linked in the README describes the connector, but may be out of date. In the case of an error, it will send a prefixed string back.

The simple Python connector (which I wanted to eventually make asynchronous via a queue and worker thread) can be used for turret integration into a webserver or other control script.

**Comment by Jenpatrick** [comment]
One last thought....
What's the wiring  on the aruduino for the following... done via relay, direct connect... Etc?

```
const int pusherSwitchPin      =  3;
const int accelerationMotorPin =  6;
const int pusherMotorPin       =  7;
const int tiltServoPin         = 10;
const int panServoPin          = 11;
const int buttonPin            = 12;
const int ledPin               = 13;
```

I'd wager the:
```
const int tiltServoPin         = 10;
const int panServoPin          = 11;
```
are just pwm in, and then ground to the 5v ground which is shared to arduino gnd, and +5 to a 5 source that also hits the ground...

But the:

```
const int pusherSwitchPin      =  3;
const int accelerationMotorPin =  6;
const int pusherMotorPin       =  7;
```

Confuses me a bit.

Danke

**Comment by brianlevis** [comment]
No problem! The Arduino is connected to that relay and the turret sensor, with resistors in-between. Here is a picture of how I have things wired up.

![](https://raw.githubusercontent.com/brianlevis/nerf-iron-dome/master/images/labeled_board.jpg)

I also added some photos to that Google Photos album that show the electronics in some more detail.

There are several limit switches that act as sensors in the gun. The only one I have wired up is one that indicates whether the firing pin is in or out (`pusherSwitchPin`). `accelerationMotorPin` and `pusherMotorPin` connect to the relay. The `servoPin`s are indeed just the PWM data pin. The Arduino shares a ground with the 6V supply that is hooked up to the servos and the motors (via relay). The Arduino also shares a ground with the 12V supply (not sure if necessary), and the Pi via USB.

The `buttonPin` and `ledPin` were just for debugging.

**Comment by Jenpatrick** [comment]
Last question(s) (I hope)

Whats the exact run/install process?

Like I setup it up as:

$~/home/me/repos/: python3 -m venv nerf
$ git clone https://github.com/brianlevis/nerf-iron-dome.git
$ cd nerf-iron-dome
$ pip -r install requirments.txt


SET flask envs:

export FLASK_APP="server.py"
export FLASK_ENV="production"
export FLASK_DEBUG="1"


Which nets me constant restarting.....

```
FLASK_APP=server.py flask  run --host=0.0.0.0
 * Serving Flask-SocketIO app "server.py"
 * Forcing debug mode on
 * Restarting with stat  ---- Just restarts the app doesn't throw good debugging info in the web page... ?
 * Debugger is active!
 * Debugger PIN: 390-330-490
CLIENT CONNECTED
received:1
```

And no video  and am using the PI-Camera 2 
Board is an Arduino Mega
Pins are all plugged in..

No Xbox controller as of yet...

Any thoughts?

I fear slightly my python3 virtualenv install might be borked, so I might just nuke it from orbit....   But if you can tell me how to get this into debug mode, I can kind of track a few things more down...

**Comment by brianlevis** [comment]
I do not have the means to test this server right now, and I was not the contributor who wrote it :( I recommend just trying to debug by getting single functionalities to work. Like saving a camera image (if applicable), building the Arduino code, separately testing all the mechanical functions, and finally getting `nerf_turret.py` to work.

I have been working with the files `modes/face_detect.py`, `ball_tracking.py` (both require OpenCV and the command `sudo modprobe bcm2835-v4l2` to be run at login), and `controller.py`.

The only things you might need to install are OpenCV (this is not trivial on Pi - check pyimagesearch for some great instructions), and (recommended) Arduino compiler on the pi so that you can edit and compile without switching cables.

The above "instructions" are applicable to our own setup, so just ignore any irrelevant parts. As you can see from the repo, this is not a polished project - the files are disorganized and the code is messy because this has just been a place for my friends and I to collaborate and share progress.

Sorry for the delayed response - I'm always happy to answer questions :D
